export const fakeProducts = [
  {
    id: 0,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская c очень длинным названием",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 1,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 2,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 3,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 4,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 5,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 6,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 7,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 8,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 9,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 10,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
  {
    id: 11,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 12,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 13,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 14,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 15,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 16,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 17,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 18,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 19,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 20,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 21,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
  {
    id: 22,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 23,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 24,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 25,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 26,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 27,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 28,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 29,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 30,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 31,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 32,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
  {
    id: 33,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 34,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 35,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 36,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 37,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 38,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 39,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 40,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 41,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 42,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 43,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
  {
    id: 44,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 45,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 46,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 47,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 48,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 49,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 50,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 51,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 52,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 53,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 54,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
  {
    id: 55,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 56,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 57,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 58,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 59,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 60,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 61,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 62,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 63,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 64,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 65,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
  {
    id: 66,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 67,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 68,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 69,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 70,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 71,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 72,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 73,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 74,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 75,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 76,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
  {
    id: 77,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 78,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 79,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 80,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 81,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 82,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 83,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 84,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 85,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 86,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 87,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
  {
    id: 88,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 89,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 90,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 91,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 92,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 93,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 94,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 95,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 96,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 97,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 98,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
  {
    id: 99,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 100,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 101,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 102,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 103,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 104,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 105,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 106,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 107,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 108,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 109,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
  {
    id: 110,
    count: 0,
    category: "Пицца",
    name: "Вегетарианская",
    description: "Пицца с миксом овощей и сыром.",
    imgUrl: "assets/pizza-vegetation.png",
    price: 600,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      овощи: "перец, лук, грибы, помидоры",
    },
    weight_g: 380,
  },
  {
    id: 111,
    count: 0,
    category: "Пицца",
    name: "Четыре сыра",
    description: "Пицца с миксом четырех видов сыра.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 650,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "дор блю, чеддер, пармезан, моцарелла",
    },
    weight_g: 400,
  },
  {
    id: 112,
    count: 0,
    category: "Пицца",
    name: "Мясная",
    description: "Пицца с миксом мяса: ветчина, пепперони, салями.",
    imgUrl: "assets/meat-pizza.png",
    price: 700,
    composition: {
      тесто: "пшеничное",
      соус: "томатный",
      сыр: "моцарелла",
      мясо: "ветчина, пепперони, салями",
    },
    weight_g: 420,
  },
  {
    id: 113,
    count: 0,
    category: "Пицца",
    name: "Морепродукты",
    description: "Пицца с морепродуктами: креветки, мидии, кальмары.",
    imgUrl: "assets/cheeese-pizza.png",
    price: 750,
    composition: {
      тесто: "пшеничное",
      соус: "сливочный",
      сыр: "моцарелла",
      морепродукты: "креветки, мидии, кальмары",
    },
    weight_g: 450,
  },
  {
    id: 114,
    count: 0,
    category: "Салаты",
    name: "Цезарь",
    description: "Салат с кусочками курицы, сыром пармезан и соусом Цезарь.",
    imgUrl: "assets/salad.png",
    price: 350,
    composition: {
      "листья салата": "романо, айсберг",
      курица: "жареная",
      сыр: "пармезан",
      помидоры: "вишня",
    },
    weight_g: 280,
  },
  {
    id: 115,
    count: 0,
    category: "Салаты",
    name: "Греческий",
    description: "Салат с оливками, помидорами, огурцами, перцем и фетой.",
    imgUrl: "assets/salad.png",
    price: 300,
    composition: {
      оливки: "коста",
      помидоры: "черри",
      огурцы: "свежие",
      перец: "болгарский",
      сыр: "фета",
    },
    weight_g: 250,
  },
  {
    id: 116,
    count: 0,
    category: "Напитки",
    name: "Кола",
    description: "Газированный напиток Кола 0.5л.",
    imgUrl: "assets/cola.png",
    price: 100,
    composition: { напиток: "газированный", объем: "0.5 л" },
    weight_g: 500,
  },
  {
    id: 117,
    count: 0,
    category: "Напитки",
    name: "Лимонад",
    description: "Освежающий лимонад с натуральным лимонным соком.",
    imgUrl: "assets/cola.png",
    price: 150,
    composition: { напиток: "безалкогольный", объем: "0.3 л", сок: "лимонный" },
    weight_g: 330,
  },
  {
    id: 118,
    count: 0,
    category: "Напитки",
    name: "Морс",
    description: "Фруктовый морс с малиной и черной смородиной.",
    imgUrl: "assets/cola.png",
    price: 120,
    composition: {
      напиток: "фруктовый",
      объем: "0.3 л",
      фрукты: "малина, черная смородина",
    },
    weight_g: 350,
  },
  {
    id: 119,
    count: 0,
    category: "Супы",
    name: "Грибной крем-суп",
    description: "Ароматный грибной крем-суп с картофелем и сливками.",
    imgUrl: "assets/soup.png",
    price: 250,
    composition: {
      грибы: "шампиньоны",
      картофель: "вареный",
      сливки: "20%",
      зелень: "укроп",
    },
    weight_g: 300,
  },
  {
    id: 120,
    count: 0,
    category: "Супы",
    name: "Томатный суп",
    description: "Томатный суп с мясными фрикадельками и зеленью.",
    imgUrl: "assets/soup.png",
    price: 280,
    composition: {
      помидоры: "свежие",
      мясо: "говядина",
      зелень: "петрушка",
      специи: "базилик, орегано",
    },
    weight_g: 320,
  },
];
